const currencyList = [
  { code: 'THB', name: 'Baht Tailandês',       symbol: '฿'   },
  { code: 'SEK', name: 'Coroa Sueca',            symbol: 'kr'  },
  { code: 'NOK', name: 'Coroa Norueguesa',       symbol: 'kr'  },
  { code: 'CZK', name: 'Coroa Tcheca',           symbol: 'Kč'  },
  { code: 'VND', name: 'Dong Vietnamita',        symbol: '₫'   },
  { code: 'AUD', name: 'Dólar Australiano',      symbol: 'AU$' },
  { code: 'CAD', name: 'Dólar Canadense',        symbol: 'CA$' },
  { code: 'SGD', name: 'Dólar de Singapura',     symbol: 'SG$' },
  { code: 'HKD', name: 'Dólar de Hong Kong',     symbol: 'HK$' },
  { code: 'NZD', name: 'Dólar Neozelandês',      symbol: 'NZ$' },
  { code: 'USD', name: 'Dólar Americano',        symbol: 'US$' },
  { code: 'EUR', name: 'Euro',                   symbol: '€'   },
  { code: 'HUF', name: 'Florim Húngaro',         symbol: 'Ft'  },
  { code: 'CHF', name: 'Franco Suíço',           symbol: 'Fr.' },
  { code: 'JPY', name: 'Iene Japonês',           symbol: '¥'   },
  { code: 'RON', name: 'Leu Romeno',             symbol: 'lei' },
  { code: 'EGP', name: 'Libra Egípcia',          symbol: 'E£'  },
  { code: 'GBP', name: 'Libra Esterlina',        symbol: '£'   },
  { code: 'TRY', name: 'Lira Turca',             symbol: '₺'   },
  { code: 'ARS', name: 'Peso Argentino',         symbol: 'AR$' },
  { code: 'CLP', name: 'Peso Chileno',           symbol: 'CLP$'},
  { code: 'COP', name: 'Peso Colombiano',        symbol: 'COL$'},
  { code: 'PHP', name: 'Peso Filipino',          symbol: '₱'   },
  { code: 'MXN', name: 'Peso Mexicano',          symbol: 'MX$' },
  { code: 'UYU', name: 'Peso Uruguaio',          symbol: '$U'  },
  { code: 'PLN', name: 'Zloty Polonês',          symbol: 'zł'  },
  { code: 'ZAR', name: 'Rand Sul-africano',      symbol: 'R'   },
  { code: 'BRL', name: 'Real Brasileiro',        symbol: 'R$'  },
  { code: 'MYR', name: 'Ringgit Malaio',         symbol: 'RM'  },
  { code: 'INR', name: 'Rúpia Indiana',          symbol: '₹'   },
  { code: 'IDR', name: 'Rupia Indonésia',        symbol: 'Rp'  },
  { code: 'PEN', name: 'Sol Peruano',            symbol: 'S/'  },
  { code: 'KRW', name: 'Won Sul-coreano',        symbol: '₩'   },
  { code: 'CNY', name: 'Yuan Chinês',            symbol: '¥'   }
];